name: "Test Report"

on: # yamllint disable-line rule:truthy
    workflow_run:
        workflows: ["Test Packages"]
        types:
            - "completed"

jobs:
    report:
        name: "Workflow test"
        runs-on: "ubuntu-latest"
        steps:
            - uses: actions/checkout@v3
            - uses: "dorny/test-reporter@v1"
              with:
                  artifact: "test-results"
                  name: "Workflow Report"
                  path: "./coverage/junit.xml"
                  reporter: "jest-junit"
